SELECT * FROM USER;

SELECT * FROM PASSWORD_CHANGE;

SELECT * FROM ADMINISTRATOR;

SELECT * FROM ORG_CATALOG;

SELECT * FROM ORGANIZATION;

SELECT * FROM ORG_PAYMENTS;

SELECT * FROM SPONSOR;

SELECT * FROM DRIVER;

SELECT * FROM DRIVER_ORGS;

SELECT * FROM DRIVER_ADDRESSES;

SELECT * FROM LOGIN_ATTEMPT;

SELECT * FROM POINT_CHANGE_REASON;

SELECT * FROM POINT_CHANGE;

SELECT * FROM PRODUCT;

SELECT * FROM IS_IN_CATALOG;

SELECT * FROM DRIVER_ORDER;

SELECT * FROM IS_IN_ORDER;

SELECT * FROM BELONGS_TO;

SELECT * FROM WISHLIST;

SELECT * FROM IS_IN_WISHLIST;

SELECT * FROM APPLICANT;