DROP TABLE APPLICANT CASCADE;

DROP TABLE IS_IN_WISHLIST CASCADE;

DROP TABLE WISHLIST CASCADE;

DROP TABLE BELONGS_TO CASCADE;

DROP TABLE IS_IN_ORDER CASCADE;

DROP TABLE DRIVER_ORDER CASCADE;

DROP TABLE IS_IN_CATALOG CASCADE;

DROP TABLE PRODUCT CASCADE;

DROP TABLE POINT_CHANGE CASCADE;

DROP TABLE POINT_CHANGE_REASON CASCADE;

DROP TABLE LOGIN_ATTEMPT CASCADE;

DROP TABLE DRIVER_ADDRESSES CASCADE;

DROP TABLE DRIVER_ORGS CASCADE;

DROP TABLE DRIVER CASCADE;

DROP TABLE SPONSOR CASCADE;

DROP TABLE ORG_PAYMENTS CASCADE;

DROP TABLE ORGANIZATION CASCADE;

DROP TABLE ORG_CATALOG CASCADE;

DROP TABLE ADMINISTRATOR CASCADE;

DROP TABLE PASSWORD_CHANGE CASCADE;

DROP TABLE USER CASCADE;