# Generated by Django 3.1.7 on 2021-03-29 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='End',
            new_name='orderDate',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Ordered',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Start',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OrderedProducts',
        ),
        migrations.DeleteModel(
            name='SearchWord',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.product'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='Catalog.OrderedProduct'),
        ),
    ]
