# Generated by Django 3.1.6 on 2021-04-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0003_auto_20210328_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
